config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  
  # 顧客用
  # URL /users/sign_in ...
  devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }
  
end

app/views/layouts/_footer.html.erb
<!--フッター-->

<footer class="footer mt-auto py-3" style="background-color: #f4a460;">
  <div class="container">
    <div class="css_font text-center">© 2023 Quick Cook.</div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #f4a460;">
    <div class="container">
      <!--ハンバーガーメニューの設定-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
        <!--管理者-->
        <li class="nav-item css_font"><%= link_to root_path,class: 'nav-link' do %>管理者1<% end %></li>
        <li class="nav-item css_font"><%= link_to root_path,class: 'nav-link' do %>管理者2<% end %></li>
        <li class="nav-item css_font"><%= link_to root_path,class: 'nav-link' do %>管理者3<% end %></li>
        <% elsif user_signed_in? %>
        <!--会員-->
        <li class="nav-item css_font"><%= link_to root_path,class: 'nav-link' do %>会員1<% end %></li>
        <li class="nav-item css_font"><%= link_to root_path,class: 'nav-link' do %>会員2<% end %></li>
        <li class="nav-item css_font"><%= link_to root_path,class: 'nav-link' do %>会員3<% end %></li>
        <% else %>
        <!--非会員-->
        <li class="nav-item css_font"><%= link_to root_path,class: 'nav-link' do %>top<% end %></li>
        <li class="nav-item css_font"><%= link_to new_user_registration_path,class: 'nav-link' do %>Sign up<% end %></li>
        <li class="nav-item css_font"><%= link_to new_user_session_path,class: 'nav-link' do %>User Sign in<% end %></li>
        <li class="nav-item css_font"><%= link_to new_admin_session_path,class: 'nav-link' do %>Admin Sign in<% end %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuickCook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/7dc7d3c10f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
      <%= render 'layouts/header' %>
      <main>
      <div class="container">
        <%= yield %>
      </div>
      </main>
      <%= render 'layouts/footer' %>
  </body>
  
</html>